#!/bin/sh

/etc/init.d/run_daemon stop
/etc/init.d/mount_daemon stop
/etc/init.d/broadcast_listener stop
sleep 5
/etc/init.d/broadcast_listener start
/etc/init.d/mount_daemon start
/etc/init.d/run_daemon start
