Document: sparse-imager
Title: Debian sparse-imager Manual
Author: <insert document author here>
Abstract: This manual describes what sparse-imager is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sparse-imager/sparse-imager.sgml.gz

Format: postscript
Files: /usr/share/doc/sparse-imager/sparse-imager.ps.gz

Format: text
Files: /usr/share/doc/sparse-imager/sparse-imager.text.gz

Format: HTML
Index: /usr/share/doc/sparse-imager/html/index.html
Files: /usr/share/doc/sparse-imager/html/*.html
